# PlotSimS - general purpose plotting, EKF related
# Copyright (C) 2023 Dave Gutz
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation;
# version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# See http://www.fsf.org/licensing/licenses/lgpl.txt for full license text.

"""Define a general purpose battery model including Randles' model and SoC-VOV model as well as Kalman filtering
support for simplified Mathworks' tracker. See Huria, Ceraolo, Gazzarri, & Jackey, 2013 Simplified Extended Kalman
Filter Observer for SOC Estimation of Commercial Power-Oriented LFP Lithium Battery Cells.
Dependencies:
    - numpy      (everything)
    - matplotlib (plots)
    - reportlab  (figures, pdf)
"""
import matplotlib.pyplot as plt
from plot.plq import plq as plq
import sys
if sys.platform == 'darwin':
    import matplotlib
    matplotlib.use('tkagg')
plt.rcParams.update({'figure.max_open_warning': 0})

def ekf_plot(mr, mv, sr, sv, smv, filename, fig_files=None, plot_title=None, fig_list=None,
             run_str='_run', ver_str='_ver', strict_overplot=False):
    print('ekf_plot', end=':  ')
    if sr and smv:
        if mr.Fx is not None:  # ekf
            fig_list.append(plt.figure())  # EKF  1
            plt.subplot(331)
            plt.title(plot_title + ' EKF 1')
            print('EKF 1', end=':  ')
            plq(plt, mr, 'time_e', mr, 'u', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'u_ekf', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(332)
            plq(plt, mr, 'time_e', mr, 'z', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'z_ekf', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(333)
            plq(plt, smv, 'time', smv, 'reset_s', color='green', linestyle='-', stairs=True)
            plq(plt, sr, 'time', sr, 'sat_s', color='blue', linestyle='--', stairs=True)
            plq(plt, smv, 'time', smv, 'sat_s', color='red', linestyle='-.', stairs=True)
            plq(plt, mv, 'time', mv, 'reset_ekf', color='orange', linestyle=':', stairs=True)
            plt.legend(loc=1)
            plt.subplot(334)
            plq(plt, mr, 'time_e', mr, 'Fx', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'Fx', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(335)
            plq(plt, mr, 'time_e', mr, 'Bu', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'Bu', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(336)
            plq(plt, mr, 'time_e', mr, 'Q', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'Q', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(337)
            plq(plt, mr, 'time_e', mr, 'R', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'R', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(338)
            plq(plt, mr, 'time_e', mr, 'P', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'P', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(339)
            plq(plt, mr, 'time_e', mr, 'S', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'S', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            fig_file_name = filename + '_' + str(len(fig_list)) + ".png"
            fig_files.append(fig_file_name)
            plt.savefig(fig_file_name, format="png")

            fig_list.append(plt.figure())  # EKF  2
            plt.subplot(331)
            plt.title(plot_title + ' EKF 2')
            print('EKF 2', end=':  ')
            plq(plt, mr, 'time_e', mr, 'K', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'K', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(332)
            plq(plt, mr, 'time_e', mr, 'x', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'x_ekf', color='red', linestyle='--', stairs=True)
            plq(plt, mr, 'time', mr, 'soc_ekf', color='cyan', linestyle='-.', stairs=True)
            plq(plt, mv, 'time', mv, 'soc_ekf', color='orange', linestyle=':', stairs=True)
            plt.legend(loc=1)
            plt.subplot(333)
            plq(plt, mr, 'time_e', mr, 'y', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'y_ekf', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(334)
            plq(plt, mr, 'time_e', mr, 'x_prior', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'x_prior', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(335)
            plq(plt, mr, 'time_e', mr, 'P_prior', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'P_prior', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(336)
            plq(plt, mr, 'time_e', mr, 'x_post', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'x_post', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(337)
            plq(plt, mr, 'time_e', mr, 'P_post', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'P_post', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(338)
            # plq(plt, mr, 'time', mr, 'voc_stat', color='blue', linestyle='-', label='voc_stat' + run_str, stairs=True)
            plq(plt, mv, 'time', mv, 'voc_stat_ekf', color='magenta', linestyle='-.', stairs=True)
            plq(plt, mr, 'time_e', mr, 'z', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'z_ekf', color='red', linestyle='--', stairs=True)
            plq(plt, mr, 'time_e', mr, 'hx', color='cyan', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'hx', color='orange', linestyle='--')
            plt.legend(loc=1)
            plt.subplot(339)
            plq(plt, mr, 'time_e', mr, 'H', color='blue', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'H', color='red', linestyle='--', stairs=True)
            plt.legend(loc=1)
            fig_file_name = filename + '_' + str(len(fig_list)) + ".png"
            fig_files.append(fig_file_name)
            plt.savefig(fig_file_name, format="png")

            fig_list.append(plt.figure())  # EKF2a
            plt.subplot(311)
            plt.title(plot_title + ' EKF 2a')
            print('EKF 2a', end=':  ')
            plq(plt, mr, 'time', mr, 'voc_stat', add=-0.0, color='red', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'voc_stat', add=-0.0, color='black', linestyle='--', stairs=True)
            plq(plt, mr, 'time_e', mr, 'z', color='cyan', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'z_ekf', color='orange', linestyle='--', stairs=True)
            plq(plt, mr, 'time_e', mr, 'hx', color='magenta', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'hx', color='green', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(312)
            plq(plt, mr, 'x', mr, 'hx', color='red', linestyle='-', stairs=True)
            plq(plt, mv, 'x_ekf', mv, 'hx', color='black', linestyle='--', stairs=True)
            plt.legend(loc=1)
            plt.subplot(313)
            plq(plt, mr, 'time', mr, 'dt', color='red', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'dt', color='black', linestyle='--', stairs=True)
            plq(plt, mr, 'time_e', mr, 'dt_ekf', color='blue', linestyle='-.', stairs=True)
            plq(plt, mv, 'time', mv, 'dt_eframe', color='orange', linestyle=':', stairs=True)
            plt.legend(loc=1)
            fig_file_name = filename + '_' + str(len(fig_list)) + ".png"
            fig_files.append(fig_file_name)
            plt.savefig(fig_file_name, format="png")

            fig_list.append(plt.figure())  # EKF3
            plt.subplot(221)
            plt.title(plot_title + ' EKF 3')
            print('EKF 3', end=':  ')
            plq(plt, mr, 'time', mr, 'ib', color='red', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'ib', color='black', linestyle='--', stairs=True)
            plq(plt, mr, 'time_e', mr, 'u', color='cyan', linestyle='-.', stairs=True)
            plq(plt, mv, 'time', mv, 'u_ekf', color='orange', linestyle=':', stairs=True)
            plt.legend(loc=1)
            plt.subplot(222)
            plq(plt, mr, 'time', mr, 'vb', color='red', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'vb', color='black', linestyle='--', stairs=True)
            plq(plt, mr, 'time_e', mr, 'z', color='cyan', linestyle='-.', stairs=True)
            plq(plt, mv, 'time', mv, 'z_ekf', color='orange', linestyle=':', stairs=True)
            plt.legend(loc=1)
            plt.subplot(223)
            plq(plt, mr, 'time', mr, 'soc', color='red', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'soc', color='black', linestyle='--', stairs=True)
            plq(plt, mr, 'time', mr, 'soc_ekf', color='cyan', linestyle='-.', stairs=True)
            plq(plt, mv, 'time', mv, 'soc_ekf', color='orange', linestyle=':', stairs=True)
            plt.legend(loc=1)
            plt.subplot(224)
            plq(plt, mr, 'time', mr, 'voc_ekf', color='red', linestyle='-', stairs=True)
            plq(plt, mv, 'time', mv, 'voc_ekf', color='black', linestyle='--', stairs=True)
            plq(plt, mr, 'time_e', mr, 'z', color='cyan', linestyle='-.', stairs=True)
            plq(plt, mv, 'time', mv, 'z_ekf', color='orange', linestyle=':', stairs=True)
            plt.legend(loc=1)

    if mr.voc_soc is not None:
        fig_list.append(plt.figure())  # EKF  4
        plt.subplot(111)
        plt.title(plot_title + ' EKF 4')
        print('EKF 4', end=':  ')
        plq(plt, mr, 'soc', mr, 'voc_stat', color='red', linestyle='-')
        plq(plt, mv, 'soc', mv, 'voc_stat', color='blue', linestyle='--')
        plq(plt, mr, 'soc', mr, 'voc_soc', color='black', linestyle='-.')
        plq(plt, mv, 'soc', mv, 'voc_soc', color='green', linestyle=':')
        plt.legend(loc=1)
        fig_file_name = filename + '_' + str(len(fig_list)) + ".png"
        fig_files.append(fig_file_name)
        plt.savefig(fig_file_name, format="png")

        fig_list.append(plt.figure())  # Hyst 1
        plt.subplot(331)
        plt.title(plot_title + ' Hyst 1')
        print('Hyst 1', end=':  ')
        # plq(plt, mr, 'time', mr, 'dv_hys_required, linestyle='-', color='black', label='dv_hys_required'+run_str)
        plq(plt, mr, 'time', mr, 'e_wrap', slr=-1, color='red', linestyle='-')
        plq(plt, mv, 'time', mv, 'e_wrap', slr=-1, color='blue', linestyle='--')
        plq(plt, mr, 'time', mr, 'e_wrap_filt', slr=-1, color='black', linestyle='-')
        plq(plt, mv, 'time', mv, 'e_wrap_filt', slr=-1, color='cyan', linestyle='--')
        plq(plt, mr, 'time', mr, 'dv_hys', color='orange', linestyle='-.')
        plq(plt, mv, 'time', mv, 'dv_hys', color='magenta', linestyle='None', marker='.', markersize='1', markevery=48)
        plq(plt, sr, 'time', sr, 'dv_hys_s', color='cyan', linestyle=':')
        plq(plt, sv, 'time', sv, 'dv_hys', color='black', linestyle='None', marker='.', markersize='1', markevery=64)
        plq(plt, smv, 'time', smv, 'dv_hys_s', color='black', linestyle='None', marker='.', markersize='1', markevery=64)
        plt.xlabel('sec')
        plt.legend(loc=4)
        plt.subplot(332)
        # plq(plt, mr, 'soc', mr, 'dv_hys_required, linestyle='-', color='black', label='dv_hys_required'+run_str)
        plq(plt, mr, 'soc', mr, 'e_wrap', slr=-1, color='red', linestyle='-')
        plq(plt, mv, 'soc', mv, 'e_wrap', slr=-1, color='blue', linestyle='--')
        plq(plt, mr, 'soc', mr, 'dv_hys', color='orange', linestyle='-.')
        plq(plt, mv, 'soc', mv, 'dv_hys', color='magenta', linestyle='None', marker='.', markersize='1', markevery=4)
        plq(plt, sr, 'soc_s', sr, 'dv_hys_s', color='cyan', linestyle=':')
        plq(plt, sv, 'soc', sv, 'dv_hys', color='black', linestyle='None', marker='.', markersize='1', markevery=5)
        plq(plt, smv, 'soc_s', smv, 'dv_hys_s', color='black', linestyle='None', marker='.', markersize='1', markevery=5)
        plt.xlabel('soc')
        plt.legend(loc=4)
        plt.subplot(333)
        plq(plt, mr, 'time', mr, 'soc', color='green', linestyle='-')
        plq(plt, mv, 'time', mv, 'soc', color='red', linestyle='--')
        plq(plt, sr, 'time', sr, 'soc_s', color='blue', linestyle='-.')
        plq(plt, sv, 'time', sv, 'soc', color='cyan', linestyle=':')
        plq(plt, smv, 'time', smv, 'soc_s', color='cyan', linestyle=':')
        plt.xlabel('sec')
        plt.legend(loc=4)
        if not strict_overplot:
            plt.subplot(334)
            plq(plt, mr, 'time', mr, 'ib_sel', color='black', linestyle='-')
            plq(plt, mr, 'time', mr, 'ioc', color='cyan', linestyle='--')
            plt.xlabel('sec')
            plt.legend(loc=4)
            plt.subplot(335)
            plq(plt, mr, 'soc', mr, 'ib_sel', color='black', linestyle='-')
            plq(plt, mr, 'soc', mr, 'ioc', color='cyan', linestyle='--')
            plt.xlabel('soc')
            plt.legend(loc=4)
            plt.subplot(336)
            plq(plt, sr, 'time', sr, 'vb_s', color='black', linestyle='-')
            plq(plt, mr, 'time', mr, 'vb', color='orange', linestyle='--')
            plq(plt, sr, 'time', sr, 'voc_stat_s', color='magenta', linestyle='-')
            plq(plt, mr, 'time', mr, 'voc_stat', color='pink', linestyle='--')
            plq(plt, mr, 'time', mr, 'voc_soc', color='black', linestyle='None', marker='.', markersize='1', markevery=32)
            plt.legend(loc=1)
            plt.subplot(337)
            plq(plt, mr, 'time', mr, 'vb', color='green', linestyle='-')
            plq(plt, mr, 'time', mr, 'voc', color='red', linestyle='--')
            plq(plt, mr, 'time', mr, 'voc_stat', color='pink', linestyle='-.')
            plq(plt, mr, 'time', mr, 'voc_soc', color='black', linestyle='None', marker='.', markersize='1', markevery=32)
            plt.xlabel('sec')
            plt.legend(loc=4)
            plt.subplot(338)
            plq(plt, mr, 'soc', mr, 'vb', color='green', linestyle='-')
            plq(plt, mr, 'soc', mr, 'voc', color='red', linestyle='--')
            plq(plt, mr, 'soc', mr, 'voc_stat', color='blue', linestyle='-.')
            plq(plt, mr, 'soc', mr, 'voc_soc', color='black', linestyle=':')
            plt.xlabel('soc')
            plt.legend(loc=4)
        plt.subplot(339)
        plq(plt, mr, 'time', mr, 'vb', color='green', linestyle='-')
        plq(plt, mv, 'time', mv, 'vb', color='orange', linestyle='--')
        plq(plt, mr, 'time', mr, 'voc', color='blue', linestyle='-.')
        plq(plt, mv, 'time', mv, 'voc', color='black', linestyle='None', marker='+', markersize='3', markevery=4)
        plq(plt, mr, 'time', mr, 'voc_stat', color='magenta', linestyle='-')
        plq(plt, mv, 'time', mv, 'voc_stat', color='pink', linestyle='--')
        plt.legend(loc=1)
        fig_file_name = filename + '_' + str(len(fig_list)) + ".png"
        fig_files.append(fig_file_name)
        plt.savefig(fig_file_name, format="png")
    return fig_list, fig_files
